version: "3.1"
services:
  teapp-app:
    build:
      args:
        user: teapp
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: teapp
    container_name: teapp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - teapp-network

  teapp-nginx:
    image: nginx:alpine
    container_name: teapp-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - teapp-network

networks:
  teapp-network:
    driver: bridge
